server:
  port: 80


spring:
  application:
    name: springcloud-order-service

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      #eureka单机版
      #defaultZone: http://eureka7001.com:7001/eureka
      #eureka集群版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: 消费者80
    prefer-ip-address: true  #显示ip