server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://121.199.8.188:3306/xuri?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: admin
    password: Admin123456.
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka # ,http://eureka7002.com:7002/eureka
  instance:
    instance-id: hystrix8001
    prefer-ip-address: true  #显示ip
    lease-renewal-interval-in-seconds: 1  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 2 #收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除

